### ISSUE TITLE
Is this project in use?

### ISSUE THREAD

**Issue by Redm0nd** [redhat-ansible-practice/ansible_gitlab_projects#1]
Hi,

I'm looking to use this module to protect master branches by default when creating a repository in a group.

Is this module in use? I'd like to look at the python files to see how it's done.

Currently have something like this in mind:

```
 ---
 - name: create a configuration repository
   gitlab_project:
     api_url: "{{ gitlab_url }}"
     api_token: "{{ gitlab_token }}"
     name: "{{ repo_name }}"
     description: "{{ description }}"
     group: "{{ gitlab_group }}"
     visibility_level: 'internal' # Internal

 - name: protect master branch by default
   gitlab_projects:
     gl_url: "{{ gitlab_url }}"
     gl_user: "Jenkins Slave"
     gl_token: "{{ gitlab_token }}"
     gl_prj_name: "{{ repo_name }}"
     gl_prj_group: "{{ gitlab_group }}"
     gl_prj_branches:
       - name: "master"
         protect: True
```
Obviously it'd be ideal to incorporate the gitlab_projects protected branch feature into the gitlab_project ansible module. 

Are there any plans to do something like this?

If it works I should be fine, nice work btw!
